version: '3'

services: 
    proxy:
        image: nginxproxy/nginx-proxy
        restart: always
        container_name: proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro   
   
    tetris:
        image: ldfishkel/tetris-solidjs
        restart: always
        container_name: tetris-solidjs
        environment:
            - VIRTUAL_HOST=foo.bar.com
            - VIRTUAL_PORT=80
            #- VIRTUAL_PORT=443
            #- VIRTUAL_PROTO=https
        ports:
            - "80"
            #- "443"
        entrypoint: node index.js
        depends_on: 
            - proxy

    
